FROM balenalib/amd64-ubuntu-python:3.9.13

# create workdir
RUN mkdir app/

# change workdir
WORKDIR /app/

# copy requirements
COPY ../requirements.txt .

# install dependencies
RUN pip install -r requirements.txt --no-cache-dir

# copy all
COPY . .

# expose ports
EXPOSE 5800
EXPOSE 5801