version: "1.0.0"

training:
  optimizer: adam
  learning_rate: 0.001
  target_update_tau: 0.05
  target_update_period: 200
  gamma: 0.99
  gradient_clipping: 10.0
  replay_buffer_capacity: 100000
  batch_size: 64
  min_replay_buffer_size: 1000
