version: "1.0.0"

training:
  epsilon_fn:
      initial_learning_rate: 1.0 # Initial learning rate
      decay_steps: 100000         # Number of steps to decay the learning rate
      end_learning_rate: 0.01
  optimizer:
    learning_rate: 0.001
  gamma: 0.99
  target_update_period: 1000
  iterations: 2000
  collect_steps_per_iteration: 1
  initial_dataset_size: 1000

env:
  discount_factor: 0.99
