name: Pylint

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint --no-cache-dir
        pip install -r requirements.deploy.txt  --no-cache-dir --no-dependencies
    - name: Analysing the code with pylint
      run: |
        pylint $(git ls-files '*.py') --disable=C0301,C0303,E0611,W0613,W0238,R0914,W0718,R0903,C0103,R0913,R0917,R1710,R0902,W0212
